//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nairc.KpwFramework.TelescopeControler
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CommandMessage", Namespace = "http://schemas.datacontract.org/2004/07/Nairc.KpwFramework.TelescopeControler")]
    public enum CommandMessage : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RaForwardFast = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RaForwardSlow = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RaBackwardFast = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RaBackwardSlow = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecForwardFast = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecForwardSlow = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecBackwardFast = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecBackwardSlow = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecStop = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        RaStop = 10,
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "Nairc.KpwFramework.TelescopeControler", ConfigurationName = "ICommandSender")]
    public interface ICommandSender
    {

        [System.ServiceModel.OperationContractAttribute(Action = "Nairc.KpwFramework.TelescopeControler/ICommandSender/Send", ReplyAction = "Nairc.KpwFramework.TelescopeControler/ICommandSender/SendResponse")]
        void Send(Nairc.KpwFramework.TelescopeControler.CommandMessage command);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICommandSenderChannel : ICommandSender, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CommandSenderClient : System.ServiceModel.ClientBase<ICommandSender>, ICommandSender
    {

        public CommandSenderClient()
        {
        }

        public CommandSenderClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public CommandSenderClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CommandSenderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public CommandSenderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public void Send(Nairc.KpwFramework.TelescopeControler.CommandMessage command)
        {
            base.Channel.Send(command);
        }
    }
}
